config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :restaurants do
    resources :reservations, only: [:show, :edit, :update, :create, :destroy]
  end
  resources :sessions, only: [:new, :create, :destroy]

  root 'restaurants#index'
end

app/models/cuisine.rb
class Cuisine < ActiveRecord::Base
  has_and_belongs_to_many :restaurants
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  validates :date_time, :party_size, presence: true
  validate :capacity_exists
  belongs_to :user
  belongs_to :restaurant

  def capacity_exists
  	# binding.pry
    existing_reservations = Reservation.where("restaurant_id = ? and date_time > ? and date_time < ?", self.restaurant_id, self.date_time.at_beginning_of_hour, self.date_time.at_end_of_hour)
    total_people = existing_reservations.sum(:party_size)
    restaurant_capacity = self.restaurant.capacity
    if (self.party_size + total_people) > restaurant_capacity
      #errors.add(:party_size, "Capacity exceeded")
      errors[:base] << "Capacity exceeded"
    end
  end

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  validates :name, :capacity, :province, :city, :street, :postal_code, :phone_number, presence: true
  has_many :reservations
  has_many :users, through: :reservations
  belongs_to :owner, class_name: "User"
  has_and_belongs_to_many :cuisines
  accepts_nested_attributes_for :cuisines

  #attr_accessible :street, :latitude, :longitude
  geocoded_by :postal_code
  after_validation :geocode
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :name, :email, presence: true
  has_many :reservations
  has_many :restaurants, through: :reservations
  has_many :owned_restaurants, class_name: "Restaurant", foreign_key: "owner_id"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def ensure_logged_in
    unless current_user
      redirect_to new_session_path
    end
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
def index
    @reservations = Reservation.all
  end

  def show
    @reservation = Reservation.find(params[:id])
  end

  def new
    @reservation = Reservation.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @reservation = @restaurant.reservations.create(reservation_params)
    @reservation.user = current_user
    if @reservation.save
      redirect_to user_path(session[:user_id])
    else
      render 'restaurants/show'
    end
  end

  def edit
    @reservation = Reservation.find(params[:id])
  end

  def update
    @reservation = Reservation.find(params[:id])
    @user = @reservation.user_id
    if @reservation.update_attributes(reservation_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    @user = @reservation.user_id
    @reservation.destroy
    redirect_to user_path(@user)
  end

  private
  def reservation_params
    params.require(:reservation).permit(:date_time, :party_size, :user_id, :restaurant_id)
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @reservation = @restaurant.reservations.build
  end

  def new
    @restaurant = Restaurant.new
    @cuisines = Cuisine.all
  end

  def create
    @cuisines = Cuisine.all
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.owner = current_user
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
    @cuisines = Cuisine.all
  end

  def update
    @restaurant = Restaurant.find(params[:id])

    if @restaurant.update_attributes(restaurant_params)
      redirect_to restaurant_path(@restaurant)
    else
      render :edit
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private
  def restaurant_params
    params.require(:restaurant).permit(:name, :capacity, :province, :city, :street, :postal_code, :phone_number, :cuisine_ids => [])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to restaurants_path
    else
      flash.now[:alert] = "Failed To log in. Email or password incorrect"
      render :new
    end
  end

  def destroy

    session[:user_id] = nil
    redirect_to restaurants_path, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  def index
    @users = User.all
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rsvp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="row container-fluid">
    <div class="col-sm-8 col-sm-offset-2">
      <div class="bg-warning">
        <% flash.each do |name, msg| -%>
          <li><%= content_tag :div, msg, class: name %></li>
        <% end %>
      </div>

      <%= yield %>

      <% if current_user %>
        <ul class="list-unstyled list-inline">
          <li><i>Signed in as <%= current_user.name %></i></li>
          <li class="btn btn-default"><%= link_to "Profile", user_path(current_user) %></li>
          <li class="btn btn-default"><%= link_to "Log out", session_path("current"), :method => :delete %></li>
        </ul>
      <% else %>
        <div>
          <%= link_to "Log in", new_session_path %> or <%= link_to "Sign up", new_user_path %>
        </div>
      <% end %>
    </div>
  </div>
</body>
</html>

app/views/reservations/edit.html.erb
<h2>Edit a reservation</h2>
<% @reservation = Reservation.find(params[:id]) %>
<% @restaurant = Restaurant.find(params[:restaurant_id]) %>

<%= form_for ([@restaurant, @reservation]) do |f| %>
  <div class="form-group">
    <%= f.datetime_select :date_time %>
  </div>
  <div class="form-group">
    <%= f.label :party_size %>
    <%= f.text_area :party_size %>
  </div>
  <div class="form-group">
    <%= f.submit %>
  </div>
<% end %>

app/views/restaurants/_display_map.erb
<%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@restaurant.latitude}%2C#{@restaurant.longitude}" %>

app/views/restaurants/_form.html.erb
<%= render partial: "/shared/errors", locals: {object: @restaurant} %>
<div class="btn btn-default">
  <%= link_to "Back to Restaurants", restaurants_url %>
</div>

<%= form_for @restaurant do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="form-group">
    <%= f.label :capacity %>
    <%= f.number_field :capacity %>
  </div>
  <div class="form-group">
    <%= f.label :province %>
    <%= f.text_field :province %>
  </div>
  <div class="form-group">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>
  <div class="form-group">
    <%= f.label :street %>
    <%= f.text_field :street %>
  </div>
  <div class="form-group">
    <%= f.label :postal_code %>
    <%= f.text_field :postal_code %>
  </div>
  <div class="form-group">
    <%= f.label :phone_number %>
    <%= f.telephone_field :phone_number %>
  </div>
  <div class="form-group">
    <% @cuisines.each do |cuisine| %>
      <%= check_box_tag "restaurant[cuisine_ids][]", cuisine.id, cuisine.id.in?(@restaurant.cuisines.collect(&:id)) %>
      <%= cuisine.name %>
    <% end %>
  </div>
  <div class="form-group">
    <%= f.submit %>
  </div>
<% end %>

app/views/restaurants/_resform.erb
<h3>Make a reservation</h3>
<%= form_for ([@restaurant, @reservation]) do |f| %>
<%= f.datetime_select :date_time %>
  <div class="form-group">
    <%= f.label :party_size %>
    <%= f.text_area :party_size %>
  </div>
  <div class="form-group">
    <%= f.submit %>
  </div>
<% end %>

app/views/restaurants/_restaurant_info.erb
<h2>Details:</h2>
<ul class="list-unstyled">
  <li>Capacity: <%= @restaurant.capacity %></li>
  <li>Address: </li>
  <li><%= @restaurant.street %></li>
  <li><%= @restaurant.city %>, <%= @restaurant.province %></li>
  <li>Postal code: <%= @restaurant.postal_code%></li>
  <li>Phone number: <%= @restaurant.phone_number%></li>
  <li>Cuisine type:
    <% @restaurant.cuisines.each do |cuisine_type| %>
    <%= cuisine_type.name %>
    <% end %>
  </li>
</ul>


<% if current_user && current_user.id == @restaurant.owner_id %>
  <ul class="list-unstyled list-inline">
    <li>
      <%= link_to "Delete", restaurant_path(@restaurant), method: :delete, data: {confirm: "Are you sure you want to delete this restaurant?"} %> 
      <%= link_to "Edit", edit_restaurant_url %>
    </li>
  </ul>
<% end %>

app/views/restaurants/_viewreservations.erb
<h3>Current reservations at <%= @restaurant.name %></h3>
<% current_user.reservations.each do |res| %>
  <% if res.restaurant_id == @restaurant.id %>
    <h4>Reservation information:</h4>
    <ul class="list-unstyled">
      <li>Date/Time: <%= res.date_time %></li>
      <li>Location: <%= res.restaurant.name %></li>
      <li>Party size: <%= res.party_size %></li>
    </ul>
  <% end %>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Edit restaurant</h1>

<%= render 'form' %>

app/views/restaurants/index.html.erb
<h1>List of Restaurants</h1>
<ul>
<% @restaurants.each do |restaurant| %>
  <li class="list-unstyled"><%= link_to restaurant.name, restaurant_path(restaurant.id) %></li>
<% end %>
</ul>

<div class="btn btn-default"><%= link_to "Add restaurant", new_restaurant_path %></div>

app/views/restaurants/new.html.erb
<h1>Add an awesome restaurant</h1>

<%= render 'form' %>

app/views/restaurants/show.html.erb
<%= link_to "Back to Restaurants", restaurants_url %>

<h1><%= @restaurant.name %></h1>

<%= render partial: "/shared/errors", locals: {object: @reservation} %>

<%= render 'restaurants/restaurant_info' %>
<%= render 'restaurants/display_map' %>

<% if current_user %>
  <%= render 'restaurants/resform' %>
  <%= render 'restaurants/viewreservations' %>
<% else %>
  <p>Login to create a reservation.</p>
<% end %>

app/views/shared/_errors.html.erb
<div>
  <% if object.errors.any? %>
    <ul class="list-unstyled">
      <% object.errors.full_messages.each do |msg| %>
        <li class="bg-warning"><%= msg %></li>
      <% end %>
    </ul>
  <% end %>
</div>

app/views/users/_form.html.erb
<%= render partial: "/shared/errors", locals: {object: @user} %>
<%= link_to "Back to Users", users_url %>


<%= form_for @user do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="form-group">
    <%= f.submit %>
  </div>

<% end %>

app/views/users/_user_info.erb
<h3>Account info</h3>
<h4>Details:</h4>
<ul class="list-unstyled">
  <li>User: <%= @user.name %></li>
  <li>E-mail: <%= @user.email %></li>
  <li>
    <%= link_to "Delete", user_path(@user), method: :delete, data: {confirm: "Are you sure you want to delete this user?"}  %> | <%= link_to "Edit", edit_user_url %>
  </li>
</ul>

<h4>Owned restaurants</h4>
<h5>Restaurant information:</h5>
<% if @user.restaurants %>
  <% @user.owned_restaurants.each do |res| %>
    <ul class="list-unstyled">
      <li>Restaurant ID: <%= res.id %></li>
      <li>Restaurant name: <%= res.name %></li>
      <li>Seating capacity: <%= res.capacity %></li>
      <li>Cuisine type:
        <% res.cuisines.each do |cuisine_type| %>
          <%= cuisine_type.name %> 
        <% end %>
      </li>
    </ul>
    <ul class="list-unstyled list-inline">
      <li>
        <%= link_to "Delete", restaurant_path(res), method: :delete, data: {confirm: "Are you sure you want to delete this restaurant?"}  %> 
        <%= link_to "Edit", edit_restaurant_path(res) %>
      </li>
    </ul>
  <% end %>
<% end %>

app/views/users/_viewreservations.erb
<h3><%= @user.name %>'s reservations</h3>
<h4>Reservation information:</h4>
<% @user.reservations.each do |res| %>
  <ul class="list-unstyled">
    <li>Reservation ID: <%= res.id %></li>
    <li>Date/Time: <%= res.date_time %></li>
    <li>Location: <%= res.restaurant.name %></li>
    <li>Party size: <%= res.party_size %></li>
  </ul>
  <ul class="list-unstyled list-inline">
    <li><%= link_to "Delete", restaurant_reservation_path(res.restaurant.id, res.id), method: :delete, data: {confirm: "Are you sure you want to delete this reservation?"} %>
    </li>
    <li>
      <%= link_to "Edit", edit_restaurant_reservation_path(res.restaurant.id, res.id) %>
    </li>
	</ul>
<% end %>

app/views/users/edit.html.erb
<h1>Edit user</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>List of Users</h1>

<% @users.each do |user| %>
  <ul class="list-unstyled">
    <li><%= link_to user.name, user_path(user.id) %></li>
    <li><%= user.email %></li>
  </ul>
<% end %>


<%= link_to "Add user", new_user_path %>

app/views/users/new.html.erb
<h1>Add new user</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<%= link_to "Back to Restaurants", restaurants_url %>

<h1><%= @user.name.capitalize  %></h1>

<%= render 'user_info' %>

<%= render 'viewreservations' %>